### ISSUE TITLE
Ensure FoldMold works on other systems (e.g. Mac) 

### ISSUE THREAD

**Issue by shakerih** [ubcspin/foldmold#33]

**Comment by shakerih** [comment]
In the past, we have not had successful builds of FoldMold on Mac systems (see the instructions in the readme file for the Windows build), possibly due to the way that the python environment is set up. It would be great to have the following:
1. write a set of instructions that allow the system to run on Mac systems as well. 
2. test the current windows build instructions on a windows machine and confirm that they work

**Comment by pbucci** [comment]
Note that this is covered by @QianqianF readme, and I've also followed this. Will add a new issue for users.
